#############################################################################
# Makefile for building: hosSmartHome
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Apr 1 18:25:20 2014
# Project:  hosSmartHome.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile hosSmartHome.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fpermissive -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -Isrc -Isrc -Iobj -Iobj
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lbluetooth -L/home/sergi/Dropbox/RPI/workspaceHos/hosSmartHome_v22/lib/libcwiid_x86 -lcwiid -lrt -lQtDeclarative -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/loggerTextEdit.cpp \
		src/amicommunicator.cpp \
		src/epuckcommunicator.cpp \
		src/hos.cpp \
		src/hoscontainer.cpp \
		src/cwiidconnector.cpp obj/moc_mainwindow.cpp \
		obj/moc_loggerTextEdit.cpp \
		obj/moc_amicommunicator.cpp \
		obj/moc_hos.cpp \
		obj/moc_hoscontainer.cpp \
		obj/moc_cwiidconnector.cpp \
		obj/qrc_hosSmartHomeResource.cpp
OBJECTS       = obj/main.o \
		obj/mainwindow.o \
		obj/loggerTextEdit.o \
		obj/amicommunicator.o \
		obj/epuckcommunicator.o \
		obj/hos.o \
		obj/hoscontainer.o \
		obj/cwiidconnector.o \
		obj/moc_mainwindow.o \
		obj/moc_loggerTextEdit.o \
		obj/moc_amicommunicator.o \
		obj/moc_hos.o \
		obj/moc_hoscontainer.o \
		obj/moc_cwiidconnector.o \
		obj/qrc_hosSmartHomeResource.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		hosSmartHome.pro
QMAKE_TARGET  = hosSmartHome
DESTDIR       = 
TARGET        = hosSmartHome

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): obj/ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hosSmartHome.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/i386-linux-gnu/libQtDeclarative.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile hosSmartHome.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/i386-linux-gnu/libQtDeclarative.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile hosSmartHome.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/hosSmartHome1.0.0 || $(MKDIR) obj/hosSmartHome1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/hosSmartHome1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/loggerTextEdit.h src/amicommunicator.h src/epuckcommunicator.h src/hos.h src/configuration.h src/sleeper_thread.h src/hoscontainer.h src/cwiidconnector.h src/util.h obj/hosSmartHome1.0.0/ && $(COPY_FILE) --parents hosSmartHomeResource.qrc obj/hosSmartHome1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/loggerTextEdit.cpp src/amicommunicator.cpp src/epuckcommunicator.cpp src/hos.cpp src/hoscontainer.cpp src/cwiidconnector.cpp obj/hosSmartHome1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui obj/hosSmartHome1.0.0/ && (cd `dirname obj/hosSmartHome1.0.0` && $(TAR) hosSmartHome1.0.0.tar hosSmartHome1.0.0 && $(COMPRESS) hosSmartHome1.0.0.tar) && $(MOVE) `dirname obj/hosSmartHome1.0.0`/hosSmartHome1.0.0.tar.gz . && $(DEL_FILE) -r obj/hosSmartHome1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: obj/moc_mainwindow.cpp obj/moc_loggerTextEdit.cpp obj/moc_amicommunicator.cpp obj/moc_hos.cpp obj/moc_hoscontainer.cpp obj/moc_cwiidconnector.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_mainwindow.cpp obj/moc_loggerTextEdit.cpp obj/moc_amicommunicator.cpp obj/moc_hos.cpp obj/moc_hoscontainer.cpp obj/moc_cwiidconnector.cpp
obj/moc_mainwindow.cpp: src/amicommunicator.h \
		src/loggerTextEdit.h \
		src/epuckcommunicator.h \
		src/bluetooth/bluetooth.h \
		src/bluetooth/rfcomm.h \
		src/cwiidconnector.h \
		src/libcwiid/cwiid.h \
		src/configuration.h \
		src/hoscontainer.h \
		src/hos.h \
		src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o obj/moc_mainwindow.cpp

obj/moc_loggerTextEdit.cpp: src/loggerTextEdit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/loggerTextEdit.h -o obj/moc_loggerTextEdit.cpp

obj/moc_amicommunicator.cpp: src/loggerTextEdit.h \
		src/amicommunicator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/amicommunicator.h -o obj/moc_amicommunicator.cpp

obj/moc_hos.cpp: src/hos.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/hos.h -o obj/moc_hos.cpp

obj/moc_hoscontainer.cpp: src/loggerTextEdit.h \
		src/hos.h \
		src/hoscontainer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/hoscontainer.h -o obj/moc_hoscontainer.cpp

obj/moc_cwiidconnector.cpp: src/libcwiid/cwiid.h \
		src/bluetooth/bluetooth.h \
		src/loggerTextEdit.h \
		src/configuration.h \
		src/cwiidconnector.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/cwiidconnector.h -o obj/moc_cwiidconnector.cpp

compiler_rcc_make_all: obj/qrc_hosSmartHomeResource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) obj/qrc_hosSmartHomeResource.cpp
obj/qrc_hosSmartHomeResource.cpp: hosSmartHomeResource.qrc \
		qml/HosHexagon.qml \
		qml/Hos.qml \
		qml/arrowBlack.png \
		qml/hexagon.png \
		qml/hexagonWhite.png \
		qml/HosHexagon.qml \
		qml/HosInner.qml
	/usr/bin/rcc -name hosSmartHomeResource hosSmartHomeResource.qrc -o obj/qrc_hosSmartHomeResource.cpp

compiler_image_collection_make_all: obj/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) obj/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: obj/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) obj/ui_mainwindow.h
obj/ui_mainwindow.h: src/mainwindow.ui
	/usr/bin/uic-qt4 src/mainwindow.ui -o obj/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp src/mainwindow.h \
		src/amicommunicator.h \
		src/loggerTextEdit.h \
		src/epuckcommunicator.h \
		src/bluetooth/bluetooth.h \
		src/bluetooth/rfcomm.h \
		src/cwiidconnector.h \
		src/libcwiid/cwiid.h \
		src/configuration.h \
		src/hoscontainer.h \
		src/hos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/amicommunicator.h \
		src/loggerTextEdit.h \
		src/epuckcommunicator.h \
		src/bluetooth/bluetooth.h \
		src/bluetooth/rfcomm.h \
		src/cwiidconnector.h \
		src/libcwiid/cwiid.h \
		src/configuration.h \
		src/hoscontainer.h \
		src/hos.h \
		obj/ui_mainwindow.h \
		src/sleeper_thread.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o src/mainwindow.cpp

obj/loggerTextEdit.o: src/loggerTextEdit.cpp src/loggerTextEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/loggerTextEdit.o src/loggerTextEdit.cpp

obj/amicommunicator.o: src/amicommunicator.cpp src/amicommunicator.h \
		src/loggerTextEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/amicommunicator.o src/amicommunicator.cpp

obj/epuckcommunicator.o: src/epuckcommunicator.cpp src/epuckcommunicator.h \
		src/bluetooth/bluetooth.h \
		src/bluetooth/rfcomm.h \
		src/loggerTextEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/epuckcommunicator.o src/epuckcommunicator.cpp

obj/hos.o: src/hos.cpp src/hos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/hos.o src/hos.cpp

obj/hoscontainer.o: src/hoscontainer.cpp src/hoscontainer.h \
		src/loggerTextEdit.h \
		src/hos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/hoscontainer.o src/hoscontainer.cpp

obj/cwiidconnector.o: src/cwiidconnector.cpp src/cwiidconnector.h \
		src/libcwiid/cwiid.h \
		src/bluetooth/bluetooth.h \
		src/loggerTextEdit.h \
		src/configuration.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cwiidconnector.o src/cwiidconnector.cpp

obj/moc_mainwindow.o: obj/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o obj/moc_mainwindow.cpp

obj/moc_loggerTextEdit.o: obj/moc_loggerTextEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_loggerTextEdit.o obj/moc_loggerTextEdit.cpp

obj/moc_amicommunicator.o: obj/moc_amicommunicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_amicommunicator.o obj/moc_amicommunicator.cpp

obj/moc_hos.o: obj/moc_hos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_hos.o obj/moc_hos.cpp

obj/moc_hoscontainer.o: obj/moc_hoscontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_hoscontainer.o obj/moc_hoscontainer.cpp

obj/moc_cwiidconnector.o: obj/moc_cwiidconnector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_cwiidconnector.o obj/moc_cwiidconnector.cpp

obj/qrc_hosSmartHomeResource.o: obj/qrc_hosSmartHomeResource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_hosSmartHomeResource.o obj/qrc_hosSmartHomeResource.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/root/widgetTest/ || $(MKDIR) $(INSTALL_ROOT)/root/widgetTest/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/root/widgetTest/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/root/widgetTest/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/root/widgetTest/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/root/widgetTest/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

